name: gabbly
description: An interactive communication app for early language development.
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  easy_sidemenu: ^0.6.1
  reorderables: ^0.6.0
  auto_scaffold: ^1.1.3
  flutter_svg: ^2.0.17
  flutter_colorpicker: ^1.0.3
  google_fonts: ^6.1.0
  image_picker: ^1.1.2
  flutter_image_compress: ^2.1.0
  path_provider: ^2.0.15
  path: ^1.9.0
  flutter_tts: ^4.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_launcher: ^6.3.1
  crypto: ^3.0.3
  logging: ^1.2.0
  introduction_screen: ^3.1.17
  flutter_heatmap_calendar: ^1.0.5
  fl_chart: ^0.63.0
  intl: ^0.18.1


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.14.3

dependency_overrides:
  async: ^2.13.0
  fake_async: ^1.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/placeholder.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
