final Map<String, List<Map<String, String>>> categories = {
  "Fruits": [
    {"word": "Apple", "imageUrl": "assets/images/apple.webp"},
    {"word": "Banana", "imageUrl": "assets/images/banana.webp"},
    {"word": "Orange", "imageUrl": "assets/images/orange.webp"},
    {"word": "Grapes", "imageUrl": "assets/images/grapes.webp"},
    {"word": "Strawberry", "imageUrl": "assets/images/strawberry.webp"},
    {"word": "Watermelon", "imageUrl": "assets/images/watermelon.webp"},
    {"word": "Pineapple", "imageUrl": "assets/images/pineapple.webp"},
    {"word": "Mango", "imageUrl": "assets/images/mango.webp"},
    {"word": "Pear", "imageUrl": "assets/images/pear.webp"},
    {"word": "Kiwi", "imageUrl": "assets/images/kiwi.webp"},
  ],
  "Animals": [
    {"word": "Cat", "imageUrl": "assets/images/cat.webp"},
    {"word": "Dog", "imageUrl": "assets/images/dog.webp"},
    {"word": "Elephant", "imageUrl": "assets/images/elephant.webp"},
    {"word": "Lion", "imageUrl": "assets/images/lion.webp"},
    {"word": "Tiger", "imageUrl": "assets/images/tiger.webp"},
    {"word": "Bear", "imageUrl": "assets/images/bear.webp"},
    {"word": "Monkey", "imageUrl": "assets/images/monkey.webp"},
    {"word": "Rabbit", "imageUrl": "assets/images/rabbit.webp"},
    {"word": "Frog", "imageUrl": "assets/images/frog.webp"},
    {"word": "Bird", "imageUrl": "assets/images/bird.webp"},
  ],
  "Basic Words": [
    {"word": "Hello", "imageUrl": "assets/images/placeholder.png"},
    {"word": "Yes", "imageUrl": "assets/images/placeholder.png"},
    {"word": "No", "imageUrl": "assets/images/placeholder.png"},
    {"word": "More", "imageUrl": "assets/images/placeholder.png"},
    {"word": "Stop", "imageUrl": "assets/images/placeholder.png"},
    {"word": "Thank You", "imageUrl": "assets/images/placeholder.png"},
    {"word": "Please", "imageUrl": "assets/images/placeholder.png"},
    {"word": "Goodbye", "imageUrl": "assets/images/placeholder.png"},
    {"word": "Sorry", "imageUrl": "assets/images/placeholder.png"},
    {"word": "Excuse", "imageUrl": "assets/images/placeholder.png"},
    {"word": "Hungry", "imageUrl": "assets/images/placeholder.png"},
    {"word": "Go", "imageUrl": "assets/images/placeholder.png"},
    {"word": "Bed", "imageUrl": "assets/images/placeholder.png"},
    {"word": "Okay", "imageUrl": "assets/images/placeholder.png"},
  ],
  "Toys": [
    {"word": "Play Dough", "imageUrl": "assets/images/placeholder.png"},
    {"word": "Barbie", "imageUrl": "assets/images/placeholder.png"},
    {"word": "Bluey", "imageUrl": "assets/images/placeholder.png"},
    {"word": "Cars", "imageUrl": "assets/images/placeholder.png"},
    {"word": "Stuffies", "imageUrl": "assets/images/placeholder.png"},
  ],
  "Vehicles": [
    {"word": "Car", "imageUrl": "assets/images/placeholder.png"},
    {"word": "Bus", "imageUrl": "assets/images/placeholder.png"},
    {"word": "Bicycle", "imageUrl": "assets/images/placeholder.png"},
    {"word": "Train", "imageUrl": "assets/images/placeholder.png"},
    {"word": "Airplane", "imageUrl": "assets/images/placeholder.png"},
    {"word": "Truck", "imageUrl": "assets/images/placeholder.png"},
    {"word": "Boat", "imageUrl": "assets/images/placeholder.png"},
    {"word": "Scooter", "imageUrl": "assets/images/placeholder.png"},
  ],
  "Colors": [
    {"word": "Red", "imageUrl": "assets/images/red.webp"},
    {"word": "Blue", "imageUrl": "assets/images/blue.webp"},
    {"word": "Green", "imageUrl": "assets/images/green.webp"},
    {"word": "Yellow", "imageUrl": "assets/images/yellow.webp"},
    {"word": "Purple", "imageUrl": "assets/images/purple.webp"},
    {"word": "Orange", "imageUrl": "assets/images/color_orange.webp"},
    {"word": "Pink", "imageUrl": "assets/images/pink.webp"},
    {"word": "Brown", "imageUrl": "assets/images/brown.webp"},
  ],
  "Foods": [
    {"word": "Bread", "imageUrl": "assets/images/placeholder.png"},
    {"word": "Milk", "imageUrl": "assets/images/placeholder.png"},
    {"word": "Cheese", "imageUrl": "assets/images/placeholder.pngg"},
    {"word": "Egg", "imageUrl": "assets/images/placeholder.png"},
    {"word": "Rice", "imageUrl": "assets/images/placeholder.png"},
    {"word": "Pasta", "imageUrl": "assets/images/pasta.png"},
    {"word": "Yogurt", "imageUrl": "assets/images/placeholder.png"},
    {"word": "Cereal", "imageUrl": "assets/images/placeholder.png"},
  ],
  "Activity": [
    {"word": "Potty", "imageUrl": "assets/images/potty.png"},
    {"word": "Help", "imageUrl": "assets/images/help.png"},
    {"word": "Clean", "imageUrl": "assets/images/clean.png"},
    {"word": "Read", "imageUrl": "assets/images/read.png"},
    {"word": "Jump", "imageUrl": "assets/images/jump.png"},
    {"word": "Sit", "imageUrl": "assets/images/sit.png"},
    {"word": "Stand", "imageUrl": "assets/images/stand.png"},
  ],
  "Essentials": [
    {"word": "Mom", "imageUrl": "assets/images/mom.png"},
    {"word": "Dad", "imageUrl": "assets/images/dad.png"},
    {"word": "Eat", "imageUrl": "assets/images/eat.png"},
    {"word": "Drink", "imageUrl": "assets/images/drink.png"},
    {"word": "Sleep", "imageUrl": "assets/images/sleep.png"},
    {"word": "Play", "imageUrl": "assets/images/play.png"},
    {"word": "Bath", "imageUrl": "assets/images/bath.png"},
    {"word": "Hug", "imageUrl": "assets/images/hug.png"},
    {"word": "Love", "imageUrl": "assets/images/love.png"},
    {"word": "All Done", "imageUrl": "assets/images/alldone.png"},
  ],
  "Emotions": [
    {"word": "Happy", "imageUrl": "assets/images/happy.png"},
    {"word": "Sad", "imageUrl": "assets/images/sad.png"},
    {"word": "Angry", "imageUrl": "assets/images/angry.png"},
    {"word": "Excited", "imageUrl": "assets/images/excited.png"},
    {"word": "Scared", "imageUrl": "assets/images/scared.png"},
    {"word": "Calm", "imageUrl": "assets/images/calm.png"},
    {"word": "Tired", "imageUrl": "assets/images/tired.png"},
    {"word": "Silly", "imageUrl": "assets/images/silly.png"},
    {"word": "Bored", "imageUrl": "assets/images/bored.png"},
    {"word": "Cheerful", "imageUrl": "assets/images/cheerful.png"},
  ],
  "Family": [
    {"word": "Brother", "imageUrl": "assets/images/brother.png"},
    {"word": "Sister", "imageUrl": "assets/images/sister.png"},
    {"word": "Grandma", "imageUrl": "assets/images/grandma.png"},
    {"word": "Grandpa", "imageUrl": "assets/images/grandpa.png"},
    {"word": "Aunt", "imageUrl": "assets/images/aunt.png"},
    {"word": "Uncle", "imageUrl": "assets/images/uncle.png"},
    {"word": "Cousin", "imageUrl": "assets/images/cousin.png"},
    {"word": "Family", "imageUrl": "assets/images/family.png"},
    {"word": "Home", "imageUrl": "assets/images/home.png"},
  ],
  "Actions": [
    {"word": "Run", "imageUrl": "assets/images/run.png"},
    {"word": "Walk", "imageUrl": "assets/images/walk.png"},
    {"word": "Dance", "imageUrl": "assets/images/dance.png"},
    {"word": "Sing", "imageUrl": "assets/images/sing.png"},
    {"word": "Color", "imageUrl": "assets/images/draw.png"},
    {"word": "Open", "imageUrl": "assets/images/open.png"},
    {"word": "Close", "imageUrl": "assets/images/close.png"},
    {"word": "Look", "imageUrl": "assets/images/look.png"},
    {"word": "Touch", "imageUrl": "assets/images/touch.png"},
    {"word": "Throw", "imageUrl": "assets/images/throw.png"},
    {"word": "Play", "imageUrl": "assets/images/play.png"},
  ],
};
