final Map<String, List<Map<String, String>>> categories = {
  // Original Categories
  "Fruits": [
    {"word": "Apple", "imageUrl": "assets/images/apple.webp"},
    {"word": "Banana", "imageUrl": "assets/images/banana.webp"},
    {"word": "Orange", "imageUrl": "assets/images/orange.webp"},
    {"word": "Grapes", "imageUrl": "assets/images/grapes.webp"},
    {"word": "Strawberry", "imageUrl": "assets/images/strawberry.webp"},
    {"word": "Watermelon", "imageUrl": "assets/images/watermelon.webp"},
    {"word": "Pineapple", "imageUrl": "assets/images/pineapple.webp"},
    {"word": "Mango", "imageUrl": "assets/images/mango.webp"},
    {"word": "Pear", "imageUrl": "assets/images/pear.webp"},
    {"word": "Kiwi", "imageUrl": "assets/images/kiwi.webp"},
  ],
  "Animals": [
    {"word": "Cat", "imageUrl": "assets/images/cat.webp"},
    {"word": "Dog", "imageUrl": "assets/images/dog.webp"},
    {"word": "Elephant", "imageUrl": "assets/images/elephant.webp"},
    {"word": "Lion", "imageUrl": "assets/images/lion.webp"},
    {"word": "Tiger", "imageUrl": "assets/images/tiger.webp"},
    {"word": "Bear", "imageUrl": "assets/images/bear.webp"},
    {"word": "Monkey", "imageUrl": "assets/images/monkey.webp"},
    {"word": "Rabbit", "imageUrl": "assets/images/rabbit.webp"},
    {"word": "Frog", "imageUrl": "assets/images/frog.webp"},
    {"word": "Bird", "imageUrl": "assets/images/bird.webp"},
  ],
  "Basic Words": [
    {"word": "Hello", "imageUrl": "assets/images/hello.png"},
    {"word": "Yes", "imageUrl": "assets/images/yes.png"},
    {"word": "No", "imageUrl": "assets/images/no.png"},
    {"word": "More", "imageUrl": "assets/images/more.png"},
    {"word": "Stop", "imageUrl": "assets/images/stop.png"},
    {"word": "Thank You", "imageUrl": "assets/images/thankyou.png"},
    {"word": "Please", "imageUrl": "assets/images/please.png"},
    {"word": "Goodbye", "imageUrl": "assets/images/goodbye.png"},
    {"word": "Sorry", "imageUrl": "assets/images/sorry.png"},
    {"word": "Excuse", "imageUrl": "assets/images/excuse.png"},
    {"word": "Hungry", "imageUrl": "assets/images/hungry.png"},
    {"word": "Go", "imageUrl": "assets/images/go.png"},
    {"word": "Bed", "imageUrl": "assets/images/bed.png"},
    {"word": "Okay", "imageUrl": "assets/images/okay.png"},
  ],
  "Toys": [
    {"word": "Play Dough", "imageUrl": "assets/images/playdough.png"},
    {"word": "Barbie", "imageUrl": "assets/images/barbie.png"},
    {"word": "Bluey", "imageUrl": "assets/images/bluey.png"},
    {"word": "Cars", "imageUrl": "assets/images/cars.png"},
    {"word": "Stuffies", "imageUrl": "assets/images/stuffies.png"},
    {"word": "Blocks", "imageUrl": "assets/images/blocks.png"},
    {"word": "Ball", "imageUrl": "assets/images/ball.png"},
    {"word": "Puzzle", "imageUrl": "assets/images/puzzle.png"},
    {"word": "Bubbles", "imageUrl": "assets/images/bubbles.png"},
    {"word": "Doll", "imageUrl": "assets/images/doll.png"},
  ],
  "Vehicles": [
    {"word": "Car", "imageUrl": "assets/images/car.png"},
    {"word": "Bus", "imageUrl": "assets/images/bus.png"},
    {"word": "Bicycle", "imageUrl": "assets/images/bicycle.png"},
    {"word": "Train", "imageUrl": "assets/images/train.png"},
    {"word": "Airplane", "imageUrl": "assets/images/airplane.png"},
    {"word": "Truck", "imageUrl": "assets/images/truck.png"},
    {"word": "Boat", "imageUrl": "assets/images/boat.png"},
    {"word": "Scooter", "imageUrl": "assets/images/scooter.png"},
    {"word": "Motorcycle", "imageUrl": "assets/images/motorcycle.png"},
    {"word": "Helicopter", "imageUrl": "assets/images/helicopter.png"},
  ],
  "Colors": [
    {"word": "Red", "imageUrl": "assets/images/red.webp"},
    {"word": "Blue", "imageUrl": "assets/images/blue.webp"},
    {"word": "Green", "imageUrl": "assets/images/green.webp"},
    {"word": "Yellow", "imageUrl": "assets/images/yellow.webp"},
    {"word": "Purple", "imageUrl": "assets/images/purple.webp"},
    {"word": "Orange", "imageUrl": "assets/images/color_orange.webp"},
    {"word": "Pink", "imageUrl": "assets/images/pink.webp"},
    {"word": "Brown", "imageUrl": "assets/images/brown.webp"},
    {"word": "Black", "imageUrl": "assets/images/black.webp"},
    {"word": "White", "imageUrl": "assets/images/white.webp"},
  ],
  "Foods": [
    {"word": "Bread", "imageUrl": "assets/images/bread.png"},
    {"word": "Milk", "imageUrl": "assets/images/milk.png"},
    {"word": "Cheese", "imageUrl": "assets/images/cheese.png"},
    {"word": "Egg", "imageUrl": "assets/images/egg.png"},
    {"word": "Rice", "imageUrl": "assets/images/rice.png"},
    {"word": "Pasta", "imageUrl": "assets/images/pasta.png"},
    {"word": "Yogurt", "imageUrl": "assets/images/yogurt.png"},
    {"word": "Cereal", "imageUrl": "assets/images/cereal.png"},
    {"word": "Chicken", "imageUrl": "assets/images/chicken.png"},
    {"word": "Pizza", "imageUrl": "assets/images/pizza.png"},
    {"word": "Soup", "imageUrl": "assets/images/soup.png"},
    {"word": "Sandwich", "imageUrl": "assets/images/sandwich.png"},
  ],
  "Activity": [
    {"word": "Potty", "imageUrl": "assets/images/potty.png"},
    {"word": "Help", "imageUrl": "assets/images/help.png"},
    {"word": "Clean", "imageUrl": "assets/images/clean.png"},
    {"word": "Read", "imageUrl": "assets/images/read.png"},
    {"word": "Jump", "imageUrl": "assets/images/jump.png"},
    {"word": "Sit", "imageUrl": "assets/images/sit.png"},
    {"word": "Stand", "imageUrl": "assets/images/stand.png"},
    {"word": "Swim", "imageUrl": "assets/images/swim.png"},
    {"word": "Draw", "imageUrl": "assets/images/draw.png"},
    {"word": "Paint", "imageUrl": "assets/images/paint.png"},
  ],
  "Essentials": [
    {"word": "Mom", "imageUrl": "assets/images/mom.png"},
    {"word": "Dad", "imageUrl": "assets/images/dad.png"},
    {"word": "Eat", "imageUrl": "assets/images/eat.png"},
    {"word": "Drink", "imageUrl": "assets/images/drink.png"},
    {"word": "Sleep", "imageUrl": "assets/images/sleep.png"},
    {"word": "Play", "imageUrl": "assets/images/play.png"},
    {"word": "Bath", "imageUrl": "assets/images/bath.png"},
    {"word": "Hug", "imageUrl": "assets/images/hug.png"},
    {"word": "Love", "imageUrl": "assets/images/love.png"},
    {"word": "All Done", "imageUrl": "assets/images/alldone.png"},
  ],
  "Emotions": [
    {"word": "Happy", "imageUrl": "assets/images/happy.png"},
    {"word": "Sad", "imageUrl": "assets/images/sad.png"},
    {"word": "Angry", "imageUrl": "assets/images/angry.png"},
    {"word": "Excited", "imageUrl": "assets/images/excited.png"},
    {"word": "Scared", "imageUrl": "assets/images/scared.png"},
    {"word": "Calm", "imageUrl": "assets/images/calm.png"},
    {"word": "Tired", "imageUrl": "assets/images/tired.png"},
    {"word": "Silly", "imageUrl": "assets/images/silly.png"},
    {"word": "Bored", "imageUrl": "assets/images/bored.png"},
    {"word": "Cheerful", "imageUrl": "assets/images/cheerful.png"},
  ],
  "Family": [
    {"word": "Brother", "imageUrl": "assets/images/brother.png"},
    {"word": "Sister", "imageUrl": "assets/images/sister.png"},
    {"word": "Grandma", "imageUrl": "assets/images/grandma.png"},
    {"word": "Grandpa", "imageUrl": "assets/images/grandpa.png"},
    {"word": "Aunt", "imageUrl": "assets/images/aunt.png"},
    {"word": "Uncle", "imageUrl": "assets/images/uncle.png"},
    {"word": "Cousin", "imageUrl": "assets/images/cousin.png"},
    {"word": "Family", "imageUrl": "assets/images/family.png"},
    {"word": "Home", "imageUrl": "assets/images/home.png"},
    {"word": "Pet", "imageUrl": "assets/images/pet.png"},
  ],
  "Actions": [
    {"word": "Run", "imageUrl": "assets/images/run.png"},
    {"word": "Walk", "imageUrl": "assets/images/walk.png"},
    {"word": "Dance", "imageUrl": "assets/images/dance.png"},
    {"word": "Sing", "imageUrl": "assets/images/sing.png"},
    {"word": "Color", "imageUrl": "assets/images/draw.png"},
    {"word": "Open", "imageUrl": "assets/images/open.png"},
    {"word": "Close", "imageUrl": "assets/images/close.png"},
    {"word": "Look", "imageUrl": "assets/images/look.png"},
    {"word": "Touch", "imageUrl": "assets/images/touch.png"},
    {"word": "Throw", "imageUrl": "assets/images/throw.png"},
    {"word": "Play", "imageUrl": "assets/images/play.png"},
  ],
  
  // New Categories
  "Health": [
    {"word": "Pain", "imageUrl": "assets/images/pain.webp"},
    {"word": "Sick", "imageUrl": "assets/images/sick.webp"},
    {"word": "Medicine", "imageUrl": "assets/images/medicine.webp"},
    {"word": "Doctor", "imageUrl": "assets/images/doctor.webp"},
    {"word": "Better", "imageUrl": "assets/images/better.webp"},
    {"word": "Hurt", "imageUrl": "assets/images/hurt.webp"},
    {"word": "Bandage", "imageUrl": "assets/images/bandage.webp"},
    {"word": "Toilet", "imageUrl": "assets/images/toilet.webp"},
    {"word": "Rest", "imageUrl": "assets/images/rest.webp"},
    {"word": "Thermometer", "imageUrl": "assets/images/thermometer.webp"},
  ],
  "Places": [
    {"word": "School", "imageUrl": "assets/images/school.webp"},
    {"word": "Park", "imageUrl": "assets/images/park.webp"},
    {"word": "Home", "imageUrl": "assets/images/home.webp"},
    {"word": "Store", "imageUrl": "assets/images/store.webp"},
    {"word": "Playground", "imageUrl": "assets/images/playground.webp"},
    {"word": "Hospital", "imageUrl": "assets/images/hospital.webp"},
    {"word": "Restaurant", "imageUrl": "assets/images/restaurant.webp"},
    {"word": "Bathroom", "imageUrl": "assets/images/bathroom.webp"},
    {"word": "Bedroom", "imageUrl": "assets/images/bedroom.webp"},
    {"word": "Kitchen", "imageUrl": "assets/images/kitchen.webp"},
  ],
  "Clothes": [
    {"word": "Shirt", "imageUrl": "assets/images/shirt.webp"},
    {"word": "Pants", "imageUrl": "assets/images/pants.webp"},
    {"word": "Shoes", "imageUrl": "assets/images/shoes.webp"},
    {"word": "Socks", "imageUrl": "assets/images/socks.webp"},
    {"word": "Jacket", "imageUrl": "assets/images/jacket.webp"},
    {"word": "Hat", "imageUrl": "assets/images/hat.webp"},
    {"word": "Underwear", "imageUrl": "assets/images/underwear.webp"},
    {"word": "Pajamas", "imageUrl": "assets/images/pajamas.webp"},
    {"word": "Coat", "imageUrl": "assets/images/coat.webp"},
    {"word": "Glasses", "imageUrl": "assets/images/glasses.webp"},
  ],
  "Body Parts": [
    {"word": "Head", "imageUrl": "assets/images/head.webp"},
    {"word": "Hand", "imageUrl": "assets/images/hand.webp"},
    {"word": "Foot", "imageUrl": "assets/images/foot.webp"},
    {"word": "Eye", "imageUrl": "assets/images/eye.webp"},
    {"word": "Ear", "imageUrl": "assets/images/ear.webp"},
    {"word": "Mouth", "imageUrl": "assets/images/mouth.webp"},
    {"word": "Nose", "imageUrl": "assets/images/nose.webp"},
    {"word": "Tummy", "imageUrl": "assets/images/tummy.webp"},
    {"word": "Back", "imageUrl": "assets/images/back.webp"},
    {"word": "Teeth", "imageUrl": "assets/images/teeth.webp"},
  ],
  "Weather": [
    {"word": "Rain", "imageUrl": "assets/images/rain.webp"},
    {"word": "Snow", "imageUrl": "assets/images/snow.webp"},
    {"word": "Sunny", "imageUrl": "assets/images/sunny.webp"},
    {"word": "Cloudy", "imageUrl": "assets/images/cloudy.webp"},
    {"word": "Wind", "imageUrl": "assets/images/wind.webp"},
    {"word": "Storm", "imageUrl": "assets/images/storm.webp"},
    {"word": "Hot", "imageUrl": "assets/images/hot_weather.webp"},
    {"word": "Cold", "imageUrl": "assets/images/cold_weather.webp"},
    {"word": "Rainbow", "imageUrl": "assets/images/rainbow.webp"},
    {"word": "Foggy", "imageUrl": "assets/images/foggy.webp"},
  ],
  "School": [
    {"word": "Teacher", "imageUrl": "assets/images/teacher.webp"},
    {"word": "Book", "imageUrl": "assets/images/book.webp"},
    {"word": "Pencil", "imageUrl": "assets/images/pencil.webp"},
    {"word": "Paper", "imageUrl": "assets/images/paper.webp"},
    {"word": "Scissors", "imageUrl": "assets/images/scissors.webp"},
    {"word": "Glue", "imageUrl": "assets/images/glue.webp"},
    {"word": "Backpack", "imageUrl": "assets/images/backpack.webp"},
    {"word": "Lunch", "imageUrl": "assets/images/lunch.webp"},
    {"word": "Friend", "imageUrl": "assets/images/friend.webp"},
    {"word": "Classroom", "imageUrl": "assets/images/classroom.webp"},
  ],
  "Time": [
    {"word": "Morning", "imageUrl": "assets/images/morning.webp"},
    {"word": "Night", "imageUrl": "assets/images/night.webp"},
    {"word": "Today", "imageUrl": "assets/images/today.webp"},
    {"word": "Tomorrow", "imageUrl": "assets/images/tomorrow.webp"},
    {"word": "Later", "imageUrl": "assets/images/later.webp"},
    {"word": "Now", "imageUrl": "assets/images/now.webp"},
    {"word": "Wait", "imageUrl": "assets/images/wait.webp"},
    {"word": "Soon", "imageUrl": "assets/images/soon.webp"},
    {"word": "Finished", "imageUrl": "assets/images/finished.webp"},
    {"word": "Schedule", "imageUrl": "assets/images/schedule.webp"},
  ],
  "Questions": [
    {"word": "What", "imageUrl": "assets/images/what.webp"},
    {"word": "Where", "imageUrl": "assets/images/where.webp"},
    {"word": "When", "imageUrl": "assets/images/when.webp"},
    {"word": "Who", "imageUrl": "assets/images/who.webp"},
    {"word": "Why", "imageUrl": "assets/images/why.webp"},
    {"word": "How", "imageUrl": "assets/images/how.webp"},
    {"word": "Can I", "imageUrl": "assets/images/can_i.webp"},
    {"word": "Help me", "imageUrl": "assets/images/help_me.webp"},
    {"word": "Show me", "imageUrl": "assets/images/show_me.webp"},
    {"word": "I want", "imageUrl": "assets/images/i_want.webp"},
  ],
  "Sensory": [
    {"word": "Loud", "imageUrl": "assets/images/loud.webp"},
    {"word": "Quiet", "imageUrl": "assets/images/quiet.webp"},
    {"word": "Bright", "imageUrl": "assets/images/bright.webp"},
    {"word": "Dark", "imageUrl": "assets/images/dark.webp"},
    {"word": "Soft", "imageUrl": "assets/images/soft.webp"},
    {"word": "Hard", "imageUrl": "assets/images/hard.webp"},
    {"word": "Sticky", "imageUrl": "assets/images/sticky.webp"},
    {"word": "Wet", "imageUrl": "assets/images/wet.webp"},
    {"word": "Dry", "imageUrl": "assets/images/dry.webp"},
    {"word": "Itchy", "imageUrl": "assets/images/itchy.webp"},
  ],
};